/*
 * Name: Calvin Ip
 * Date: April 16, 2021
 * Version: 1.0
 * Description: Second Window for VideoGameMainApp.java database
 *           
 */
package edu.hdsb.gwss.ics4u.u6;

import java.awt.Color;

/**
 *
 * @author ICS4U-Calvin
 */
public class AddVideoGame extends javax.swing.JFrame {

    private VideoGameMainApp parent;
    private int id;

    /**
     * Creates new form AddVideoGame
     */
    public AddVideoGame() {
        initComponents();
    }

    /*
    * Constructor for New/Save object
     */
    public AddVideoGame(VideoGameMainApp parent) {
        initComponents();

        //Reference Main Window
        this.parent = parent;

        //Set Title (Add Video Game)
        this.jLabelTitle.setText("Add Video Game");

    }

    /*
    * Constructor for Update object
     */
    public AddVideoGame(VideoGameMainApp parent, int id) {
        initComponents();

        //Reference Main Window
        this.parent = parent;

        //Set Title (Update Video Game)
        this.jLabelTitle.setText("Update Video Game");
        
        //Change Name of Save Button
        this.jButtonAdd.setText("Save");

        VideoGameRecord vgOld = new VideoGameRecord();

        //Read from database
        vgOld = VideoGameDB.read(id);

        //Set items in the fields for user to edit and update
        //Name
        this.jTextFieldName.setText(vgOld.getName().trim());
        //System
        this.jComboBoxSystem.setSelectedItem(vgOld.getSystem().trim());
        //Genre
        this.jTextFieldGenre.setText(vgOld.getGenre().trim());
        //Sold
        this.jSpinnerSold.setValue(vgOld.getSold());
        //Rank
        this.jSpinnerRank.setValue(vgOld.getRank());
        //Price
        this.jTextFieldPrice.setText(vgOld.getPrice() + "");
        //Grade
        this.jComboBoxGrade.setSelectedItem(String.valueOf(vgOld.getGrade()));
        //Released True or False
        this.jCheckBoxReleased.setSelected(vgOld.isReleased());
        
        //Set Id
        this.id = id;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopBackground = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBackground = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelSystem = new javax.swing.JLabel();
        jLabelGenre = new javax.swing.JLabel();
        jLabelSold = new javax.swing.JLabel();
        jLabelReleased = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxSystem = new javax.swing.JComboBox<>();
        jSpinnerSold = new javax.swing.JSpinner();
        jCheckBoxReleased = new javax.swing.JCheckBox();
        jTextFieldGenre = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabelRank = new javax.swing.JLabel();
        jSpinnerRank = new javax.swing.JSpinner();
        jLabelGrade = new javax.swing.JLabel();
        jComboBoxGrade = new javax.swing.JComboBox<>();
        jLabelErrorMessage = new javax.swing.JLabel();
        jLabelNameValid = new javax.swing.JLabel();
        jLabelPriceValid = new javax.swing.JLabel();
        jLabelSystemValid = new javax.swing.JLabel();
        jLabelGenreValid = new javax.swing.JLabel();
        jLabelSoldValid = new javax.swing.JLabel();
        jLabelRankValid = new javax.swing.JLabel();
        jLabelGradeValid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelTopBackground.setBackground(new java.awt.Color(255, 204, 204));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Add Video Game");
        jLabelTitle.setToolTipText("");

        javax.swing.GroupLayout jPanelTopBackgroundLayout = new javax.swing.GroupLayout(jPanelTopBackground);
        jPanelTopBackground.setLayout(jPanelTopBackgroundLayout);
        jPanelTopBackgroundLayout.setHorizontalGroup(
            jPanelTopBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBackgroundLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopBackgroundLayout.setVerticalGroup(
            jPanelTopBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelBackground.setBackground(new java.awt.Color(204, 204, 204));

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelName.setText("Name: ");

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPrice.setText("Price: ");

        jLabelSystem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSystem.setText("System:");

        jLabelGenre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelGenre.setText("Genre:");

        jLabelSold.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSold.setText("# Sold:");

        jLabelReleased.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelReleased.setText("Released:");

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jComboBoxSystem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxSystem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Switch", "Xbox One X", "PS5", "PC", "Other" }));
        jComboBoxSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSystemActionPerformed(evt);
            }
        });

        jTextFieldGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenreActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonAdd.setText("Add To Database");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelRank.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelRank.setText("Rank:");

        jLabelGrade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelGrade.setText("Grade:");

        jComboBoxGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "S", "A", "B", "C", "D", "E", "F" }));
        jComboBoxGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradeActionPerformed(evt);
            }
        });

        jLabelErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelNameValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelPriceValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelSystemValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelGenreValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelSoldValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelRankValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelGradeValid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelPrice))
                                .addGap(100, 100, 100))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelReleased)
                                    .addComponent(jLabelGrade)
                                    .addComponent(jLabelRank)
                                    .addComponent(jLabelSold))
                                .addGap(74, 74, 74)))
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxReleased)
                            .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelGradeValid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jSpinnerRank, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRankValid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jSpinnerSold, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSoldValid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jTextFieldGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelGenreValid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jComboBoxSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSystemValid))
                                .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPriceValid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jLabelNameValid))))
                        .addGap(93, 93, 93))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSystem)
                            .addComponent(jLabelGenre))
                        .addGap(54, 54, 54))))
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButtonAdd))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameValid))
                .addGap(16, 16, 16)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPriceValid))
                .addGap(18, 18, 18)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSystem)
                    .addComponent(jComboBoxSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSystemValid))
                .addGap(16, 16, 16)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGenre)
                    .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelGenreValid)))
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelSold)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerSold, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSoldValid))
                        .addGap(18, 18, 18)))
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerRank, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRankValid))
                    .addComponent(jLabelRank))
                .addGap(19, 19, 19)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelGradeValid))
                    .addComponent(jLabelGrade))
                .addGap(35, 35, 35)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReleased, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxReleased, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTopBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTopBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jComboBoxSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSystemActionPerformed

    private void jTextFieldGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenreActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        //Set Valid to True
        boolean isValid = true;

        //Create Empty Container/Object
        VideoGameRecord vg = new VideoGameRecord();

        //Store Name (String)
        String name = jTextFieldName.getText();
        if (name.length() == 0) {
            //ERROR OCCURS!
            this.jLabelNameValid.setText("Invalid");
            this.jLabelNameValid.setForeground(Color.red);

            isValid = false;
        } else {
            //Set Name in VG Object and print green valid
            vg.setName(name);

            this.jLabelNameValid.setText("Valid");
            this.jLabelNameValid.setForeground(Color.green);
        }

        //Store System (String)
        String system = (String) jComboBoxSystem.getSelectedItem();
        if (system.length() == 0) {
            //ERROR OCCURS!
            this.jLabelSystemValid.setText("Invalid");
            this.jLabelSystemValid.setForeground(Color.red);

            isValid = false;
        } else {
            //Set System in VG Object and print green valid
            vg.setSystem(system);

            this.jLabelSystemValid.setText("Valid");
            this.jLabelSystemValid.setForeground(Color.green);
        }

        //Store Genre (String)
        String genre = jTextFieldGenre.getText();
        if (genre.length() == 0) {
            //ERROR OCCURS!
            this.jLabelGenreValid.setText("Invalid");
            this.jLabelGenreValid.setForeground(Color.red);

            isValid = false;
        } else {
            //Set Genre in VG Object and print green valid
            vg.setGenre(genre);

            this.jLabelGenreValid.setText("Valid");
            this.jLabelGenreValid.setForeground(Color.green);
        }

        //Store Sold (Int)
        int sold = (int) jSpinnerSold.getValue();
        if (sold < 0) {
            //ERROR OCCURS!
            this.jLabelSoldValid.setText("Invalid");
            this.jLabelSoldValid.setForeground(Color.red);

            isValid = false;
        } else {
            //Set Sold in VG Object and print green valid
            vg.setSold(sold);

            this.jLabelSoldValid.setText("Valid");
            this.jLabelSoldValid.setForeground(Color.green);
        }

        //Store Rank (Int)
        int rank = (int) jSpinnerRank.getValue();
        if (rank <= 0) {
            //ERROR OCCURS!
            this.jLabelRankValid.setText("Invalid");
            this.jLabelRankValid.setForeground(Color.red);

            isValid = false;
        } else {
            //Set Rank in VG Object and print green valid
            vg.setRank(rank);

            this.jLabelRankValid.setText("Valid");
            this.jLabelRankValid.setForeground(Color.green);
        }

        //Store Price (Double)
        try {
            double price = Double.parseDouble(jTextFieldPrice.getText());

            if (price < 0) {
                //ERROR OCCURS!
                this.jLabelPriceValid.setText("Invalid");
                this.jLabelPriceValid.setForeground(Color.red);
                isValid = false;
            } else {
                //Set Price in VG Object and print green valid
                vg.setPrice(price);

                this.jLabelPriceValid.setText("Valid");
                this.jLabelPriceValid.setForeground(Color.green);
            }

        } catch (Exception e) {
            this.jLabelPriceValid.setText("Invalid");
            this.jLabelPriceValid.setForeground(Color.red);
            isValid = false;
        }

        //Store Boolean (No need for error checking)
        vg.setReleased(jCheckBoxReleased.isSelected());

        //Store Char
        if (jComboBoxGrade.getSelectedItem().toString().length() == 0) {
            //ERROR OCCURS!
            this.jLabelGradeValid.setText("Invalid");
            this.jLabelGradeValid.setForeground(Color.red);

            isValid = false;
        } else {
            //Set Grade in VG Object and print green valid
            vg.setGrade((jComboBoxGrade.getSelectedItem()).toString().charAt(0));

            this.jLabelGradeValid.setText("Valid");
            this.jLabelGradeValid.setForeground(Color.green);
        }

        //Store Id
        try{
            vg.setid(id);
            
        } catch (Exception e){
            e.printStackTrace();
        }       
        
        //If Error Occurs Anywhere, Print Generic Error Message
        if (!isValid) {
            this.jLabelErrorMessage.setText("ERROR! CHECK FIELDS! ENTER VALID DATA!");
        }

        //Save if Valid
        if (isValid) {
            //Open File, Write to File, Close File
            VideoGameDB.open();
            VideoGameDB.save(vg);
            VideoGameDB.close();

            //Update Dropdown, Open Main, Close This Window
            parent.populateDropDown();
            parent.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGradeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVideoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVideoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVideoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVideoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVideoGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JCheckBox jCheckBoxReleased;
    private javax.swing.JComboBox<String> jComboBoxGrade;
    private javax.swing.JComboBox<String> jComboBoxSystem;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelGenreValid;
    private javax.swing.JLabel jLabelGrade;
    private javax.swing.JLabel jLabelGradeValid;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameValid;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPriceValid;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLabel jLabelRankValid;
    private javax.swing.JLabel jLabelReleased;
    private javax.swing.JLabel jLabelSold;
    private javax.swing.JLabel jLabelSoldValid;
    private javax.swing.JLabel jLabelSystem;
    private javax.swing.JLabel jLabelSystemValid;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelTopBackground;
    private javax.swing.JSpinner jSpinnerRank;
    private javax.swing.JSpinner jSpinnerSold;
    private javax.swing.JTextField jTextFieldGenre;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
